# Generated by Django 4.2.1 on 2023-05-25 05:05

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelationsHeaderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.IntegerField()),
                ('invoice_date', models.DateField()),
                ('created_on', models.DateTimeField()),
                ('last_updated_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RelationsDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.PositiveIntegerField()),
                ('quantity', models.FloatField()),
                ('uom', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('tax', models.FloatField()),
                ('total', models.FloatField()),
                ('invoice_header_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RelationsAPP.relationsheadermodel')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
