# Generated by Django 4.2.1 on 2023-06-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelationsAPP', '0002_alter_relationsheadermodel_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationsheadermodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
