# Generated by Django 4.2.1 on 2023-06-08 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RelationsAPP', '0003_relationsheadermodel_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='relationsdetailmodel',
            managers=[
            ],
        ),
    ]
