# Generated by Django 4.2.1 on 2023-05-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoorsDetailModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('header_id', models.IntegerField()),
                ('sub_category_name', models.CharField(max_length=512)),
                ('price', models.CharField(max_length=512)),
                ('seller_name', models.CharField(max_length=512)),
                ('seller_description', models.CharField(max_length=512)),
                ('seller_rating', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='DoorsHeaderModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=512)),
                ('url', models.CharField(max_length=1024)),
                ('created_on', models.DateField(auto_now=True)),
                ('last_updated_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
