# Generated by Django 4.2.1 on 2023-05-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndiaMartAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorsdetailmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doorsheadermodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
